# Default service type is LoadBalancer, this overrides it with a ClusterIP
service:
 type: ClusterIP

# We install the Niord Theme by adding a simple container which have the binary files installed.
# An alternative could be to put it into a ConfigMap as binary values
initContainers:
  - name: theme-provider
    image: kaspernielsen/dma-niord-theme:latest
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying theme..."
        cp -R /niord_theme/* /theme
    volumeMounts:
      - name: theme
        mountPath: /theme

extraVolumeMounts:
  - name: theme
    mountPath: /opt/bitnami/keycloak/themes/niord

extraVolumes:
  - name: theme
    emptyDir: {}

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG

# We need to enable proxy address forwarding so Keycloak knows to
# translate http->https
proxyAddressForwarding: true

# setup ingress
ingress:
  enabled: "true"
  hostname: keycloak.example.com

# If you are running with a cert-manager you can uncomment the following
#  annotations:
#   cert-manager.io/cluster-issuer: "letsencrypt-staging"
#  tls: true
  
